# Generated by Django 5.2.16 on 2026-07-28 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duree_minutes', models.PositiveIntegerField(default=30)),
                ('actif', models.BooleanField(default=True)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demarches', to='citoyens.administration')),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('reserve_jusqu_a', models.DateTimeField(blank=True, null=True)),
                ('demarche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='citoyens.demarche')),
            ],
            options={
                'unique_together': {('demarche', 'date', 'heure')},
            },
        ),
    ]
