# Generated by Django 5.2.16 on 2026-07-28 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citoyens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('cle_idempotence', models.CharField(max_length=100, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('creneau', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='citoyens.creneau')),
            ],
        ),
    ]
