# Generated by Django 5.2.16 on 2026-07-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citoyens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('reserve_jusqu_a', models.DateTimeField(blank=True, null=True)),
                ('demarche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='citoyens.demarche')),
            ],
            options={
                'unique_together': {('demarche', 'date', 'heure')},
            },
        ),
    ]
